//! Interaction of `validate_admission_bindings` with native nullifier
//! proof verification, using real proofs.
//!
//! `admit` runs the two deterministic checks in the same order as
//! `validate()`. Source-chain activity, Ed25519 signatures and the SP1
//! proof need a conductor or a real SP1 proof and are not exercised here;
//! scenarios whose rejection depends on them say so explicitly.
//!
//! Throughout, the attacker holds a valid native proof generated by the
//! victim (it is public on the DHT) but not the victim's credential secret.

use std::sync::OnceLock;

use zk_admission_groth16_circuit::{generate_key_material, NullifierProvingKeyV1};
use zk_admission_protocol::{
    encoding::encode_statement,
    hashes::{capability_id, delegation_id, nullifier, statement_hash},
    validation::{validate_admission_bindings, AdmissionContextV1},
    AdmissionCapabilityV1, AdmissionConfigV1, AdmissionDelegationV1, AdmissionV1, ProtocolError,
    ProverKeyV1, SignatureV1, ZkProofEntryV1, ZkStatementV1,
};

use crate::native_groth16::check_native_nullifier_proof;

const VICTIM_SECRET: [u8; 32] = [0x11; 32];
const DEPLOYMENT_A: [u8; 32] = [0xa1; 32];
const DEPLOYMENT_B: [u8; 32] = [0xb2; 32];
const DOMAIN: [u8; 32] = [0x33; 32];
const ALICE: [u8; 32] = [0xa7; 32];
const MALLORY: [u8; 32] = [0x6d; 32];
const SEQUENCE: u32 = 8;

struct Deployment {
    proving_key: NullifierProvingKeyV1,
    config: AdmissionConfigV1,
}

impl Deployment {
    fn generate() -> Self {
        let material = generate_key_material().unwrap();

        Self {
            proving_key: NullifierProvingKeyV1::from_bytes(
                &material.proving_key_bytes,
                &material.verifying_key_fingerprint,
            )
            .unwrap(),
            config: AdmissionConfigV1 {
                admission_root_key: [0; 32],
                admission_root_key_id: [0; 32],
                issuer_root_key: [0; 32],
                issuer_root_key_id: [0; 32],
                sp1_program_vkey_hash: [3; 32],
                nullifier_groth16_vk: material.verifying_key_bytes,
                nullifier_groth16_vk_fingerprint: material.verifying_key_fingerprint,
            },
        }
    }
}

/// Deployment A's pinned key.
fn deployment_a() -> &'static Deployment {
    static D: OnceLock<Deployment> = OnceLock::new();
    D.get_or_init(Deployment::generate)
}

/// Deployment B ran its own setup.
fn deployment_b() -> &'static Deployment {
    static D: OnceLock<Deployment> = OnceLock::new();
    D.get_or_init(Deployment::generate)
}

fn statement(deployment_id: [u8; 32], prover: [u8; 32]) -> ZkStatementV1 {
    ZkStatementV1 {
        deployment_id,
        protocol_version: ZkStatementV1::PROTOCOL_VERSION,
        domain: DOMAIN,
        program_id: [3; 32],
        prover: ProverKeyV1(prover.to_vec()),
        issuer_id: [7; 32],
        issuer_key_id: [8; 32],
        credential_epoch: 42,
        statement_nonce: [9; 32],
        eligibility: true,
        nullifier: nullifier(
            &VICTIM_SECRET,
            &deployment_id,
            &DOMAIN,
            ZkStatementV1::PROTOCOL_VERSION,
        ),
    }
}

/// An operator-issued admission for exactly `statement`.
///
/// Signatures are placeholders (verified by the host, not here); scenarios
/// that call this for an attacker-modified statement model an attacker who
/// has obtained a capability for that statement.
fn admission_for(statement: &ZkStatementV1) -> AdmissionV1 {
    let mut delegation = AdmissionDelegationV1 {
        root_key_id: [11; 32],
        op_key_id: [12; 32],
        op_public_key: [13; 32],
        policy_id: [14; 32],
        allowed_resource_classes: 1 << 3,
        epoch_start: 100,
        epoch_end: 200,
        delegation_id: [0; 32],
        root_signature: SignatureV1([16; 64]),
    };
    delegation.delegation_id = delegation_id(&delegation);

    let mut capability = AdmissionCapabilityV1 {
        capability_id: [0; 32],
        delegation_id: delegation.delegation_id,
        deployment_id: statement.deployment_id,
        prover: statement.prover.clone(),
        policy_id: delegation.policy_id,
        statement_hash: statement_hash(statement),
        statement_nonce: statement.statement_nonce,
        resource_class: 3,
        admission_epoch: 150,
        seq_start: 7,
        seq_end_exclusive: 10,
        op_key_id: delegation.op_key_id,
        op_signature: SignatureV1([18; 64]),
    };
    capability.capability_id = capability_id(&capability);

    AdmissionV1 {
        delegation,
        capability,
    }
}

/// Alice's genuine entry for deployment A.
fn victim_entry() -> &'static ZkProofEntryV1 {
    static ENTRY: OnceLock<ZkProofEntryV1> = OnceLock::new();
    ENTRY.get_or_init(|| {
        let statement = statement(DEPLOYMENT_A, ALICE);

        ZkProofEntryV1 {
            admission: admission_for(&statement),
            nullifier_proof: deployment_a()
                .proving_key
                .prove_statement(&statement, &VICTIM_SECRET)
                .unwrap(),
            groth16_proof: vec![0; 356],
            statement,
        }
    })
}

/// The same entry with an attacker-modified statement and a capability
/// re-issued for it.
fn with_reissued_statement(modify: impl FnOnce(&mut ZkStatementV1)) -> ZkProofEntryV1 {
    let mut entry = victim_entry().clone();
    modify(&mut entry.statement);
    entry.admission = admission_for(&entry.statement);
    entry
}

/// Deterministic validation steps, in `validate()` order. `deployment_id`
/// is the DNA hash and `author` the action author, as in `validate()`.
fn admit(
    entry: &ZkProofEntryV1,
    deployment_id: &[u8; 32],
    author: &[u8; 32],
    config: &AdmissionConfigV1,
) -> Result<(), ProtocolError> {
    validate_admission_bindings(
        &entry.statement,
        &entry.admission,
        AdmissionContextV1 {
            deployment_id,
            author,
            candidate_sequence: SEQUENCE,
        },
    )?;

    check_native_nullifier_proof(entry, config)
}

fn admit_in_a(entry: &ZkProofEntryV1, author: &[u8; 32]) -> Result<(), ProtocolError> {
    admit(entry, &DEPLOYMENT_A, author, &deployment_a().config)
}

#[test]
fn genuine_entry_is_admitted() {
    assert_eq!(admit_in_a(victim_entry(), &ALICE), Ok(()));
}

// --- deployment ----------------------------------------------------------

#[test]
fn entry_replayed_into_another_deployment_is_rejected_by_bindings() {
    assert_eq!(
        admit(
            victim_entry(),
            &DEPLOYMENT_B,
            &ALICE,
            &deployment_b().config
        ),
        Err(ProtocolError::DeploymentMismatch)
    );
}

#[test]
fn proof_reattached_to_statement_for_another_deployment_is_rejected() {
    // Statement and capability rewritten for deployment B; the nullifier
    // cannot be recomputed for B without the secret, so it is kept.
    let entry = with_reissued_statement(|s| s.deployment_id = DEPLOYMENT_B);

    // Same pinned key (shared setup): the pairing check fails.
    assert_eq!(
        admit(&entry, &DEPLOYMENT_B, &ALICE, &deployment_a().config),
        Err(ProtocolError::NullifierProofVerificationFailed)
    );

    // Deployment B's own key: rejected by the pinned fingerprint.
    assert_eq!(
        admit(&entry, &DEPLOYMENT_B, &ALICE, &deployment_b().config),
        Err(ProtocolError::NullifierVerifyingKeyMismatch)
    );
}

#[test]
fn proof_relabelled_for_another_deployments_key_is_rejected() {
    let mut entry = with_reissued_statement(|s| s.deployment_id = DEPLOYMENT_B);
    entry.nullifier_proof.verifying_key_id = deployment_b().config.nullifier_groth16_vk_fingerprint;

    assert_eq!(
        admit(&entry, &DEPLOYMENT_B, &ALICE, &deployment_b().config),
        Err(ProtocolError::NullifierProofVerificationFailed)
    );
}

// --- domain --------------------------------------------------------------

#[test]
fn changed_domain_without_capability_is_rejected_by_bindings() {
    let mut entry = victim_entry().clone();
    entry.statement.domain = [0x44; 32];

    assert_eq!(
        admit_in_a(&entry, &ALICE),
        Err(ProtocolError::StatementHashMismatch)
    );
}

#[test]
fn changed_domain_with_reissued_capability_is_rejected_by_native_proof() {
    let entry = with_reissued_statement(|s| s.domain = [0x44; 32]);

    assert_eq!(
        admit_in_a(&entry, &ALICE),
        Err(ProtocolError::NullifierProofVerificationFailed)
    );
}

// --- nullifier -----------------------------------------------------------

#[test]
fn changed_nullifier_without_capability_is_rejected_by_bindings() {
    let mut entry = victim_entry().clone();
    entry.statement.nullifier[0] ^= 1;

    assert_eq!(
        admit_in_a(&entry, &ALICE),
        Err(ProtocolError::StatementHashMismatch)
    );
}

#[test]
fn fresh_nullifier_with_reissued_capability_is_rejected_by_native_proof() {
    // E.g. to evade nullifier-based uniqueness with a reused proof.
    let entry = with_reissued_statement(|s| s.nullifier = [0x99; 32]);

    assert_eq!(
        admit_in_a(&entry, &ALICE),
        Err(ProtocolError::NullifierProofVerificationFailed)
    );
}

// --- author / prover -----------------------------------------------------

#[test]
fn victim_entry_authored_by_attacker_is_rejected_by_bindings() {
    assert_eq!(
        admit_in_a(victim_entry(), &MALLORY),
        Err(ProtocolError::ProverMismatch)
    );
}

#[test]
fn statement_prover_must_match_capability_prover() {
    let mut entry = victim_entry().clone();
    entry.statement.prover = ProverKeyV1(MALLORY.to_vec());

    assert_eq!(
        admit_in_a(&entry, &MALLORY),
        Err(ProtocolError::ProverMismatch)
    );
}

#[test]
fn native_proof_alone_does_not_bind_the_author_so_sp1_remains_required() {
    // Mallory reuses Alice's public native proof and nullifier under her
    // own key, with a capability issued to Mallory for that statement.
    let entry = with_reissued_statement(|s| s.prover = ProverKeyV1(MALLORY.to_vec()));

    // Bindings and the native proof both accept: the circuit has no
    // prover input.
    assert_eq!(admit_in_a(&entry, &MALLORY), Ok(()));

    // What rejects it in `validate()` is the SP1 proof, whose public
    // values are the full canonical statement: Alice's SP1 proof commits
    // to Alice as prover, and a new one needs Alice's secret.
    assert_ne!(
        encode_statement(&entry.statement),
        encode_statement(&victim_entry().statement)
    );
}

// --- statement nonce -----------------------------------------------------

#[test]
fn changed_statement_nonce_is_rejected_by_bindings() {
    let mut entry = victim_entry().clone();
    entry.statement.statement_nonce = [0x77; 32];

    assert_eq!(
        admit_in_a(&entry, &ALICE),
        Err(ProtocolError::StatementHashMismatch)
    );
}

#[test]
fn capability_nonce_must_match_statement_nonce() {
    let mut entry = victim_entry().clone();
    entry.admission.capability.statement_nonce = [0x77; 32];
    entry.admission.capability.capability_id = capability_id(&entry.admission.capability);

    assert_eq!(
        admit_in_a(&entry, &ALICE),
        Err(ProtocolError::CapabilityIdMismatch)
    );
}

#[test]
fn native_proof_alone_does_not_bind_the_nonce_so_sp1_remains_required() {
    let entry = with_reissued_statement(|s| s.statement_nonce = [0x77; 32]);

    assert_eq!(admit_in_a(&entry, &ALICE), Ok(()));
    assert_ne!(
        encode_statement(&entry.statement),
        encode_statement(&victim_entry().statement)
    );
}

// --- capability statement hash -------------------------------------------

#[test]
fn tampered_capability_statement_hash_is_rejected_by_capability_id() {
    let mut entry = victim_entry().clone();
    entry.admission.capability.statement_hash[0] ^= 1;

    assert_eq!(
        admit_in_a(&entry, &ALICE),
        Err(ProtocolError::CapabilityIdMismatch)
    );
}

#[test]
fn tampered_capability_statement_hash_with_recomputed_id_is_rejected() {
    // Recomputing the id is possible for anyone; the operator signature
    // over it (checked by the host) is not, but bindings already reject.
    let mut entry = victim_entry().clone();
    entry.admission.capability.statement_hash[0] ^= 1;
    entry.admission.capability.capability_id = capability_id(&entry.admission.capability);

    assert_eq!(
        admit_in_a(&entry, &ALICE),
        Err(ProtocolError::StatementHashMismatch)
    );
}

#[test]
fn capability_for_another_statement_cannot_carry_this_proof() {
    // A capability legitimately issued for a different domain is attached
    // to the victim statement and proof.
    let mut other = statement(DEPLOYMENT_A, ALICE);
    other.domain = [0x44; 32];

    let mut entry = victim_entry().clone();
    entry.admission = admission_for(&other);

    assert_eq!(
        admit_in_a(&entry, &ALICE),
        Err(ProtocolError::StatementHashMismatch)
    );
}

// --- pinned key and proof encoding at the zome boundary ------------------

#[test]
fn verifying_key_id_must_match_dna_pinned_fingerprint() {
    let mut entry = victim_entry().clone();
    entry.nullifier_proof.verifying_key_id[0] ^= 1;

    assert_eq!(
        admit_in_a(&entry, &ALICE),
        Err(ProtocolError::NullifierVerifyingKeyMismatch)
    );
}

#[test]
fn inconsistent_dna_key_configuration_is_rejected() {
    // Deployment B's key bytes under deployment A's fingerprint.
    let mut config = deployment_a().config.clone();
    config.nullifier_groth16_vk = deployment_b().config.nullifier_groth16_vk.clone();

    assert_eq!(
        admit(victim_entry(), &DEPLOYMENT_A, &ALICE, &config),
        Err(ProtocolError::InvalidNullifierVerifyingKey)
    );
}

#[test]
fn malformed_native_proof_is_rejected() {
    let mut entry = victim_entry().clone();
    entry.nullifier_proof.proof.truncate(100);

    assert_eq!(
        admit_in_a(&entry, &ALICE),
        Err(ProtocolError::InvalidNullifierProof)
    );
}
