[package]
name = "zk-admission-prover"
version.workspace = true
edition.workspace = true

[lib]
name = "zk_admission_prover"
path = "src/lib.rs"

[dependencies]
sp1-sdk = { version = "=6.8.1", features = ["blocking"] }
zk-admission-protocol = { path = "../protocol" }
zk-admission-groth16-verifier = { path = "../groth16-verifier" }
sha2 = "0.10"
hex = "0.4.3"
ark-bn254 = "0.5.0"
ark-groth16 = "0.5.0"
ark-relations = "0.5.1"
ark-r1cs-std = "0.5.0"
ark-std = "0.5.0"
ark-snark = "0.5.1"
ark-serialize = "0.5.0"
ark-crypto-primitives = { version = "0.5.0", features = ["crh", "r1cs", "std"] }
